/** Base columns from client product_template.csv (Shopify new CSV format). */
export const SHOPIFY_BASE_COLUMNS = [
  "Title",
  "URL handle",
  "Description",
  "Vendor",
  "Product category",
  "Type",
  "Tags",
  "Published on online store",
  "Status",
  "SKU",
  "Barcode",
  "Option1 name",
  "Option1 value",
  "Option1 Linked To",
  "Option2 name",
  "Option2 value",
  "Option2 Linked To",
  "Option3 name",
  "Option3 value",
  "Option3 Linked To",
  "Price",
  "Compare-at price",
  "Cost per item",
  "Charge tax",
  "Tax code",
  "Unit price total measure",
  "Unit price total measure unit",
  "Unit price base measure",
  "Unit price base measure unit",
  "Inventory tracker",
  "Inventory quantity",
  "Continue selling when out of stock",
  "Weight value (grams)",
  "Weight unit for display",
  "Requires shipping",
  "Fulfillment service",
  "Product image URL",
  "Image position",
  "Image alt text",
  "Variant image URL",
  "Gift card",
  "SEO title",
  "SEO description",
  "Color (product.metafields.shopify.color-pattern)",
  "Google Shopping / Google product category",
  "Google Shopping / Gender",
  "Google Shopping / Age group",
  "Google Shopping / Manufacturer part number (MPN)",
  "Google Shopping / Ad group name",
  "Google Shopping / Ads labels",
  "Google Shopping / Condition",
  "Google Shopping / Custom product",
  "Google Shopping / Custom label 0",
  "Google Shopping / Custom label 1",
  "Google Shopping / Custom label 2",
  "Google Shopping / Custom label 3",
  "Google Shopping / Custom label 4",
] as const;

/** Client store Polish custom metafield columns (from screenshots). */
export const SHOPIFY_CUSTOM_METAFIELD_COLUMNS = [
  "Rozmiar (product.metafields.custom.rozmiar)",
  "Producent (product.metafields.custom.producent)",
  "Stan (product.metafields.custom.stan)",
  "Kod produktu: (product.metafields.custom.kod_produktu_)",
  "Skład (product.metafields.custom.sk_ad)",
  "Szerokość od pachy do pachy (product.metafields.custom.szeroko_od_pachy_do_pachy_)",
  "Długość tył (product.metafields.custom.d_ugo_ty_)",
  "Szerokość Talia (product.metafields.custom.szeroko_talia)",
  "Długość rękawa (product.metafields.custom.d_ugo_r_kawa)",
  "Rozmiar pod biustem (product.metafields.custom.underbust)",
  "Wzór (product.metafields.custom.wz_r)",
  "Fabric (product.metafields.shopify.fabric)",
] as const;

export const SHOPIFY_PRODUCT_IMPORT_COLUMNS = [
  ...SHOPIFY_BASE_COLUMNS,
  ...SHOPIFY_CUSTOM_METAFIELD_COLUMNS,
] as const;

export type ShopifyCsvColumn = (typeof SHOPIFY_PRODUCT_IMPORT_COLUMNS)[number];
